#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("_9gag.Resource", IsApplication=true)]

namespace _9gag
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::_9gag.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::_9gag.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::_9gag.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::_9gag.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::_9gag.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::_9gag.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::_9gag.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::_9gag.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::_9gag.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::_9gag.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::_9gag.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::_9gag.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::_9gag.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::_9gag.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::_9gag.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::_9gag.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::_9gag.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::_9gag.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::_9gag.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::_9gag.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::_9gag.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxBind = global::_9gag.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxDropDownItemTemplate = global::_9gag.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxGroupItemTemplate = global::_9gag.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxItemTemplate = global::_9gag.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxLang = global::_9gag.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxSource = global::_9gag.Resource.Attribute.MvxSource;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxTemplate = global::_9gag.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxTemplateSelector = global::_9gag.Resource.Attribute.MvxTemplateSelector;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollEnabled = global::_9gag.Resource.Attribute.fastScrollEnabled;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollHorizontalThumbDrawable = global::_9gag.Resource.Attribute.fastScrollHorizontalThumbDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollHorizontalTrackDrawable = global::_9gag.Resource.Attribute.fastScrollHorizontalTrackDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollVerticalThumbDrawable = global::_9gag.Resource.Attribute.fastScrollVerticalThumbDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollVerticalTrackDrawable = global::_9gag.Resource.Attribute.fastScrollVerticalTrackDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.font = global::_9gag.Resource.Attribute.font;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderAuthority = global::_9gag.Resource.Attribute.fontProviderAuthority;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderCerts = global::_9gag.Resource.Attribute.fontProviderCerts;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderFetchStrategy = global::_9gag.Resource.Attribute.fontProviderFetchStrategy;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderFetchTimeout = global::_9gag.Resource.Attribute.fontProviderFetchTimeout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderPackage = global::_9gag.Resource.Attribute.fontProviderPackage;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderQuery = global::_9gag.Resource.Attribute.fontProviderQuery;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontStyle = global::_9gag.Resource.Attribute.fontStyle;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontWeight = global::_9gag.Resource.Attribute.fontWeight;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.layoutManager = global::_9gag.Resource.Attribute.layoutManager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.reverseLayout = global::_9gag.Resource.Attribute.reverseLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.spanCount = global::_9gag.Resource.Attribute.spanCount;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.stackFromEnd = global::_9gag.Resource.Attribute.stackFromEnd;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Boolean.abc_action_bar_embed_tabs = global::_9gag.Resource.Boolean.abc_action_bar_embed_tabs;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Color.notification_action_color_filter = global::_9gag.Resource.Color.notification_action_color_filter;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Color.notification_icon_bg_color = global::_9gag.Resource.Color.notification_icon_bg_color;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Color.ripple_material_light = global::_9gag.Resource.Color.ripple_material_light;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Color.secondary_text_default_material_light = global::_9gag.Resource.Color.secondary_text_default_material_light;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_button_inset_horizontal_material = global::_9gag.Resource.Dimension.compat_button_inset_horizontal_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_button_inset_vertical_material = global::_9gag.Resource.Dimension.compat_button_inset_vertical_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_button_padding_horizontal_material = global::_9gag.Resource.Dimension.compat_button_padding_horizontal_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_button_padding_vertical_material = global::_9gag.Resource.Dimension.compat_button_padding_vertical_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_control_corner_material = global::_9gag.Resource.Dimension.compat_control_corner_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.fastscroll_default_thickness = global::_9gag.Resource.Dimension.fastscroll_default_thickness;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.fastscroll_margin = global::_9gag.Resource.Dimension.fastscroll_margin;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.fastscroll_minimum_range = global::_9gag.Resource.Dimension.fastscroll_minimum_range;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::_9gag.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity = global::_9gag.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_swipe_escape_velocity = global::_9gag.Resource.Dimension.item_touch_helper_swipe_escape_velocity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_action_icon_size = global::_9gag.Resource.Dimension.notification_action_icon_size;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_action_text_size = global::_9gag.Resource.Dimension.notification_action_text_size;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_big_circle_margin = global::_9gag.Resource.Dimension.notification_big_circle_margin;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_content_margin_start = global::_9gag.Resource.Dimension.notification_content_margin_start;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_large_icon_height = global::_9gag.Resource.Dimension.notification_large_icon_height;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_large_icon_width = global::_9gag.Resource.Dimension.notification_large_icon_width;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_main_column_padding_top = global::_9gag.Resource.Dimension.notification_main_column_padding_top;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_media_narrow_margin = global::_9gag.Resource.Dimension.notification_media_narrow_margin;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_right_icon_size = global::_9gag.Resource.Dimension.notification_right_icon_size;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_right_side_padding_top = global::_9gag.Resource.Dimension.notification_right_side_padding_top;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_small_icon_background_padding = global::_9gag.Resource.Dimension.notification_small_icon_background_padding;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_small_icon_size_as_large = global::_9gag.Resource.Dimension.notification_small_icon_size_as_large;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_subtext_size = global::_9gag.Resource.Dimension.notification_subtext_size;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_top_pad = global::_9gag.Resource.Dimension.notification_top_pad;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_top_pad_large_text = global::_9gag.Resource.Dimension.notification_top_pad_large_text;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_action_background = global::_9gag.Resource.Drawable.notification_action_background;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg = global::_9gag.Resource.Drawable.notification_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_low = global::_9gag.Resource.Drawable.notification_bg_low;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_low_normal = global::_9gag.Resource.Drawable.notification_bg_low_normal;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_low_pressed = global::_9gag.Resource.Drawable.notification_bg_low_pressed;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_normal = global::_9gag.Resource.Drawable.notification_bg_normal;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_normal_pressed = global::_9gag.Resource.Drawable.notification_bg_normal_pressed;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_icon_background = global::_9gag.Resource.Drawable.notification_icon_background;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_template_icon_bg = global::_9gag.Resource.Drawable.notification_template_icon_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_template_icon_low_bg = global::_9gag.Resource.Drawable.notification_template_icon_low_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_tile_bg = global::_9gag.Resource.Drawable.notification_tile_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notify_panel_notification_icon_bg = global::_9gag.Resource.Drawable.notify_panel_notification_icon_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.MvvmCrossTagId = global::_9gag.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.MvxBindingTagUnique = global::_9gag.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.action_container = global::_9gag.Resource.Id.action_container;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.action_divider = global::_9gag.Resource.Id.action_divider;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.action_image = global::_9gag.Resource.Id.action_image;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.action_text = global::_9gag.Resource.Id.action_text;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.actions = global::_9gag.Resource.Id.actions;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.async = global::_9gag.Resource.Id.async;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.blocking = global::_9gag.Resource.Id.blocking;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.chronometer = global::_9gag.Resource.Id.chronometer;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.forever = global::_9gag.Resource.Id.forever;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.icon = global::_9gag.Resource.Id.icon;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.icon_group = global::_9gag.Resource.Id.icon_group;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.info = global::_9gag.Resource.Id.info;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.italic = global::_9gag.Resource.Id.italic;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.item_touch_helper_previous_elevation = global::_9gag.Resource.Id.item_touch_helper_previous_elevation;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.line1 = global::_9gag.Resource.Id.line1;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.line3 = global::_9gag.Resource.Id.line3;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.normal = global::_9gag.Resource.Id.normal;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.notification_background = global::_9gag.Resource.Id.notification_background;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.notification_main_column = global::_9gag.Resource.Id.notification_main_column;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.notification_main_column_container = global::_9gag.Resource.Id.notification_main_column_container;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.right_icon = global::_9gag.Resource.Id.right_icon;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.right_side = global::_9gag.Resource.Id.right_side;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.tag_transition_group = global::_9gag.Resource.Id.tag_transition_group;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.text = global::_9gag.Resource.Id.text;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.text2 = global::_9gag.Resource.Id.text2;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.time = global::_9gag.Resource.Id.time;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.title = global::_9gag.Resource.Id.title;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Integer.status_bar_notification_info_maxnum = global::_9gag.Resource.Integer.status_bar_notification_info_maxnum;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_action = global::_9gag.Resource.Layout.notification_action;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_action_tombstone = global::_9gag.Resource.Layout.notification_action_tombstone;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_template_custom_big = global::_9gag.Resource.Layout.notification_template_custom_big;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_template_icon_group = global::_9gag.Resource.Layout.notification_template_icon_group;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_template_part_chronometer = global::_9gag.Resource.Layout.notification_template_part_chronometer;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_template_part_time = global::_9gag.Resource.Layout.notification_template_part_time;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.String.status_bar_notification_info_overflow = global::_9gag.Resource.String.status_bar_notification_info_overflow;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification = global::_9gag.Resource.Style.TextAppearance_Compat_Notification;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification_Info = global::_9gag.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::_9gag.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification_Time = global::_9gag.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification_Title = global::_9gag.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.Widget_Compat_NotificationActionContainer = global::_9gag.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.Widget_Compat_NotificationActionText = global::_9gag.Resource.Style.Widget_Compat_NotificationActionText;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily = global::_9gag.Resource.Styleable.FontFamily;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderAuthority = global::_9gag.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderCerts = global::_9gag.Resource.Styleable.FontFamily_fontProviderCerts;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::_9gag.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::_9gag.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderPackage = global::_9gag.Resource.Styleable.FontFamily_fontProviderPackage;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderQuery = global::_9gag.Resource.Styleable.FontFamily_fontProviderQuery;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont = global::_9gag.Resource.Styleable.FontFamilyFont;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_android_font = global::_9gag.Resource.Styleable.FontFamilyFont_android_font;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_android_fontStyle = global::_9gag.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_android_fontWeight = global::_9gag.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_font = global::_9gag.Resource.Styleable.FontFamilyFont_font;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_fontStyle = global::_9gag.Resource.Styleable.FontFamilyFont_fontStyle;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_fontWeight = global::_9gag.Resource.Styleable.FontFamilyFont_fontWeight;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding = global::_9gag.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding_MvxBind = global::_9gag.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding_MvxLang = global::_9gag.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxControl = global::_9gag.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxControl_MvxTemplate = global::_9gag.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxExpandableListView = global::_9gag.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::_9gag.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxImageView = global::_9gag.Resource.Styleable.MvxImageView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxImageView_MvxSource = global::_9gag.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView = global::_9gag.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::_9gag.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView_MvxItemTemplate = global::_9gag.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxRecyclerView = global::_9gag.Resource.Styleable.MvxRecyclerView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxRecyclerView_MvxTemplateSelector = global::_9gag.Resource.Styleable.MvxRecyclerView_MvxTemplateSelector;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView = global::_9gag.Resource.Styleable.RecyclerView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_android_descendantFocusability = global::_9gag.Resource.Styleable.RecyclerView_android_descendantFocusability;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_android_orientation = global::_9gag.Resource.Styleable.RecyclerView_android_orientation;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollEnabled = global::_9gag.Resource.Styleable.RecyclerView_fastScrollEnabled;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollHorizontalThumbDrawable = global::_9gag.Resource.Styleable.RecyclerView_fastScrollHorizontalThumbDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollHorizontalTrackDrawable = global::_9gag.Resource.Styleable.RecyclerView_fastScrollHorizontalTrackDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollVerticalThumbDrawable = global::_9gag.Resource.Styleable.RecyclerView_fastScrollVerticalThumbDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollVerticalTrackDrawable = global::_9gag.Resource.Styleable.RecyclerView_fastScrollVerticalTrackDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_layoutManager = global::_9gag.Resource.Styleable.RecyclerView_layoutManager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_reverseLayout = global::_9gag.Resource.Styleable.RecyclerView_reverseLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_spanCount = global::_9gag.Resource.Styleable.RecyclerView_spanCount;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_stackFromEnd = global::_9gag.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010013
			public const int MvxBind = 2130771987;
			
			// aapt resource value: 0x7f010017
			public const int MvxDropDownItemTemplate = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int MvxGroupItemTemplate = 2130771992;
			
			// aapt resource value: 0x7f010016
			public const int MvxItemTemplate = 2130771990;
			
			// aapt resource value: 0x7f010014
			public const int MvxLang = 2130771988;
			
			// aapt resource value: 0x7f010019
			public const int MvxSource = 2130771993;
			
			// aapt resource value: 0x7f010015
			public const int MvxTemplate = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int MvxTemplateSelector = 2130771986;
			
			// aapt resource value: 0x7f010004
			public const int fastScrollEnabled = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int fastScrollHorizontalThumbDrawable = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fastScrollHorizontalTrackDrawable = 2130771976;
			
			// aapt resource value: 0x7f010005
			public const int fastScrollVerticalThumbDrawable = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int fastScrollVerticalTrackDrawable = 2130771974;
			
			// aapt resource value: 0x7f010010
			public const int font = 2130771984;
			
			// aapt resource value: 0x7f010009
			public const int fontProviderAuthority = 2130771977;
			
			// aapt resource value: 0x7f01000c
			public const int fontProviderCerts = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int fontProviderFetchStrategy = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fontProviderFetchTimeout = 2130771982;
			
			// aapt resource value: 0x7f01000a
			public const int fontProviderPackage = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int fontProviderQuery = 2130771979;
			
			// aapt resource value: 0x7f01000f
			public const int fontStyle = 2130771983;
			
			// aapt resource value: 0x7f010011
			public const int fontWeight = 2130771985;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int abc_action_bar_embed_tabs = 2131230720;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090000
			public const int notification_action_color_filter = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int notification_icon_bg_color = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int ripple_material_light = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int secondary_text_default_material_light = 2131296259;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f05000a
			public const int compat_button_inset_horizontal_material = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int compat_button_inset_vertical_material = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int compat_button_padding_horizontal_material = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int compat_button_padding_vertical_material = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int compat_control_corner_material = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int fastscroll_default_thickness = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int fastscroll_margin = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int fastscroll_minimum_range = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int item_touch_helper_swipe_escape_max_velocity = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int item_touch_helper_swipe_escape_velocity = 2131034117;
			
			// aapt resource value: 0x7f05000f
			public const int notification_action_icon_size = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int notification_action_text_size = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int notification_big_circle_margin = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int notification_content_margin_start = 2131034119;
			
			// aapt resource value: 0x7f050012
			public const int notification_large_icon_height = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int notification_large_icon_width = 2131034131;
			
			// aapt resource value: 0x7f050008
			public const int notification_main_column_padding_top = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int notification_media_narrow_margin = 2131034121;
			
			// aapt resource value: 0x7f050014
			public const int notification_right_icon_size = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int notification_right_side_padding_top = 2131034118;
			
			// aapt resource value: 0x7f050015
			public const int notification_small_icon_background_padding = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int notification_small_icon_size_as_large = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int notification_subtext_size = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int notification_top_pad = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int notification_top_pad_large_text = 2131034137;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_template_icon_low_bg = 2130837516;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int splash = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int MvvmCrossTagId = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int MvxBindingTagUnique = 2131099656;
			
			// aapt resource value: 0x7f06000f
			public const int action_container = 2131099663;
			
			// aapt resource value: 0x7f06001b
			public const int action_divider = 2131099675;
			
			// aapt resource value: 0x7f060010
			public const int action_image = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int action_text = 2131099665;
			
			// aapt resource value: 0x7f06001c
			public const int actions = 2131099676;
			
			// aapt resource value: 0x7f060009
			public const int async = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int blocking = 2131099658;
			
			// aapt resource value: 0x7f06001a
			public const int chronometer = 2131099674;
			
			// aapt resource value: 0x7f06000b
			public const int forever = 2131099659;
			
			// aapt resource value: 0x7f060013
			public const int icon = 2131099667;
			
			// aapt resource value: 0x7f06001d
			public const int icon_group = 2131099677;
			
			// aapt resource value: 0x7f060016
			public const int info = 2131099670;
			
			// aapt resource value: 0x7f06000c
			public const int italic = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_previous_elevation = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int line1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int line3 = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int normal = 2131099661;
			
			// aapt resource value: 0x7f060018
			public const int notification_background = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int notification_main_column = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int notification_main_column_container = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int right_icon = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int right_side = 2131099669;
			
			// aapt resource value: 0x7f060003
			public const int tag_transition_group = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int text = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int text2 = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int text_view_id = 2131099662;
			
			// aapt resource value: 0x7f060019
			public const int time = 2131099673;
			
			// aapt resource value: 0x7f060006
			public const int title = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0b0000
			public const int status_bar_notification_info_maxnum = 2131427328;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int item_list = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int MainView = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_action = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_action_tombstone = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_template_custom_big = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_template_icon_group = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int notification_template_part_chronometer = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int notification_template_part_time = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int SplashScreen = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070002
			public const int app_name = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int hello = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int status_bar_notification_info_overflow = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int TextAppearance_Compat_Notification = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int TextAppearance_Compat_Notification_Info = 2131361793;
			
			// aapt resource value: 0x7f0a0006
			public const int TextAppearance_Compat_Notification_Line2 = 2131361798;
			
			// aapt resource value: 0x7f0a0002
			public const int TextAppearance_Compat_Notification_Time = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int TextAppearance_Compat_Notification_Title = 2131361795;
			
			// aapt resource value: 0x7f0a0007
			public const int Theme_Splash = 2131361799;
			
			// aapt resource value: 0x7f0a0004
			public const int Widget_Compat_NotificationActionContainer = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int Widget_Compat_NotificationActionText = 2131361797;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			public static int[] MvxBinding = new int[] {
					2130771987,
					2130771988};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771989};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771992};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771993};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771990,
					2130771991};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] MvxRecyclerView = new int[] {
					2130771986};
			
			// aapt resource value: 0
			public const int MvxRecyclerView_MvxTemplateSelector = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 6
			public const int RecyclerView_fastScrollEnabled = 6;
			
			// aapt resource value: 9
			public const int RecyclerView_fastScrollHorizontalThumbDrawable = 9;
			
			// aapt resource value: 10
			public const int RecyclerView_fastScrollHorizontalTrackDrawable = 10;
			
			// aapt resource value: 7
			public const int RecyclerView_fastScrollVerticalThumbDrawable = 7;
			
			// aapt resource value: 8
			public const int RecyclerView_fastScrollVerticalTrackDrawable = 8;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
